---
title: "GapMap Citation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
  “COVID-19 Map.” Johns Hopkins Coronavirus Resource Center, coronavirus.jhu.edu/map.html.
  GitHub: https://github.com/govex/COVID-19/tree/master/data_tables
  
  “COVID-19 Pandemic.” Wikipedia, Wikimedia Foundation, 7 May 2020, 
  en.wikipedia.org/wiki/COVID-19_pandemic.

  Bhaskar Karambelkar and Barret Schloerke (2018). leaflet.extras: Extra
  Functionality for 'leaflet' Package. R package version 1.0.0.
  https://CRAN.R-project.org/package=leaflet.extras
  
  Simon Garnier (2018). viridis: Default Color Maps from 'matplotlib'. R
  package version 0.5.1. https://CRAN.R-project.org/package=viridis
  
  Pebesma, E., 2018. Simple Features for R: Standardized Support for Spatial
  Vector Data. The R Journal 10 (1), 439-446,
  https://doi.org/10.32614/RJ-2018-009
  
  Jim Hester (2019). glue: Interpreted String Literals. R package version
  1.3.1. https://CRAN.R-project.org/package=glue
  
  Joe Cheng, Bhaskar Karambelkar and Yihui Xie (2019). leaflet: Create
  Interactive Web Maps with the JavaScript 'Leaflet' Library. R package
  version 2.0.3. https://CRAN.R-project.org/package=leaflet
  
  Hadley Wickham and Lionel Henry (2020). tidyr: Tidy Messy Data. R package
  version 1.0.2. https://CRAN.R-project.org/package=tidyr
  
  Wickham et al., (2019). Welcome to the tidyverse. Journal of Open Source
  Software, 4(43), 1686, https://doi.org/10.21105/joss.01686
  
  Kyle Walker (2020). tidycensus: Load US Census Boundary and Attribute Data
  as 'tidyverse' and 'sf'-Ready Data Frames. R package version 0.9.9.2.
  https://CRAN.R-project.org/package=tidycensus
  
  Winston Chang (2018). shinythemes: Themes for Shiny. R package version
  1.1.2. https://CRAN.R-project.org/package=shinythemes
  
  Winston Chang and Barbara Borges Ribeiro (2018). shinydashboard: Create
  Dashboards with 'Shiny'. R package version 0.7.1.
  https://CRAN.R-project.org/package=shinydashboard
  
  Winston Chang, Joe Cheng, JJ Allaire, Yihui Xie and Jonathan McPherson
  (2019). shiny: Web Application Framework for R. R package version 1.4.0.
  https://CRAN.R-project.org/package=shiny
  
  H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag
  New York, 2016.
  
  Hadley Wickham and Lionel Henry (2020). tidyr: Tidy Messy Data. R package
  version 1.0.2. https://CRAN.R-project.org/package=tidyr


  
  

  
  
  
  
